---
- hosts: all
  tasks:
    - name: First command
      command: /bin/true
      register: result
      ignore_errors: true

    - name: Second command
      command: /bin/echo yes
      when: result is failed

    - name: First command
      command: /bin/false
      register: result
      ignore_errors: true

    - name: Second command
      command: /bin/echo yes
      when: result is failed
