---
- hosts: jessie
  tasks:
    - name: Point sources.list to Jessie
      replace: dest=/etc/apt/sources.list regexp='wheezy' replace='jessie'
      register: result
      become: yes

    - name: Update package index
      apt: update_cache=yes
      become: yes

    - name: Install update-notifier-common
      apt: name=update-notifier-common state=present
      become: yes

    - name: ensure pysparc is stopped
      supervisorctl: name=pysparc state=stopped

    - name: ensure redis-server is stopped
      service: name=redis-server state=stopped
      become: yes

    - name: Safe-upgrade packages
      apt: upgrade=safe
      become: yes

    - name: Dist-upgrade packages (1st stage)
      apt: upgrade=dist
      become: yes

    - name: Dist-upgrade packages (2nd stage)
      apt: upgrade=dist
      become: yes

    - name: Check if reboot is necessary
      stat: path=/var/run/reboot-required
      register: reboot

    # if path reboot is a regular file, trigger reboot
    - name: Flag a reboot if necessary
      command: /bin/true
      when: reboot.stat.isreg is defined
      notify: reboot

    - name: ensure redis-server is started
      service: name=redis-server state=started
      when: reboot.stat.isreg is not defined
      become: yes

    - name: ensure pysparc is started
      supervisorctl: name=pysparc state=started
      when: (reboot.stat.isreg is not defined) and (inventory_hostname != "vagrant")

  handlers:
    - include: handlers.yml
