---
- hosts: all
  tasks:
    - name: Update package index
      apt: update_cache=yes
      sudo: yes

    - name: Install update-notifier-common
      apt: name=update-notifier-common state=present
      sudo: yes

    - name: ensure pysparc is stopped
      supervisorctl: name=pysparc state=stopped

    - name: ensure redis-server is stopped
      service: name=redis-server state=stopped
      sudo: yes

    - name: Safe-upgrade packages
      apt: upgrade=safe
      sudo: yes

    - name: Check if reboot is necessary
      stat: path=/var/run/reboot-required
      register: reboot

    # if path reboot is a regular file, trigger reboot
    - name: Flag a reboot if necessary
      debug: msg="Reboot is necessary"
      when: reboot.stat.isreg is defined
      notify: reboot

    - name: ensure redis-server is started
      service: name=redis-server state=started
      when: reboot.stat.isreg is not defined
      sudo: yes

    - name: ensure pysparc is started
      supervisorctl: name=pysparc state=started
      when: (reboot.stat.isreg is not defined) and (inventory_hostname != "vagrant")

  handlers:
    - include: handlers.yml
